### ISSUE TITLE
query_all() returns None when launching the example code

### ISSUE THREAD

**Issue by d-antesque** [psolbach/metadoc#5]
Code:
```
from metadoc import Metadoc
url = 'https://theintercept.com/2016/11/17/iphones-secretly-send-call-history-to-apple-security-firm-says'
metadoc = Metadoc(url=url).query_all()
print(metadoc)
metadoc.return_ball()
```

Trace:
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    metadoc.return_ball()
AttributeError: 'NoneType' object has no attribute 'return_ball'
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<Domaintools.async_get_all() done, defined at /usr/local/lib/python3.5/dist-packages/metadoc/domain/domaintools.py:47> exception=FileNotFoundError(2, "No such file or directory: 'whois'")>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/usr/local/lib/python3.5/dist-packages/metadoc/domain/domaintools.py", line 49, in async_get_all
    return await loop.run_in_executor(None, self.get_all)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/metadoc/domain/domaintools.py", line 32, in get_all
    self.get_date_registered()
  File "/usr/local/lib/python3.5/dist-packages/metadoc/domain/domaintools.py", line 25, in get_date_registered
    self.date_registered = whois_date_registered(self.domain)
  File "/usr/local/lib/python3.5/dist-packages/metadoc/domain/lookup.py", line 9, in whois_date_registered
    query = whois.query(domain) # silently fails in corporate env, vocally fails behind proxy
  File "/usr/local/lib/python3.5/dist-packages/whois/__init__.py", line 50, in query
    pd = do_parse(do_query(d, force, cache_file, slow_down, ignore_returncode), tld)
  File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 44, in do_query
    _do_whois_query(dl, ignore_returncode),
  File "/usr/local/lib/python3.5/dist-packages/whois/_1_query.py", line 58, in _do_whois_query
    p = subprocess.Popen(['whois', '.'.join(dl)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'whois'
```

**Comment by psolbach** [comment]
You need the `whois` binary. What's your OS? Windows CMD does not ship with whois, as do some smaller footprint Linux distros.
